### ISSUE TITLE
UEFI Error after convert to OVA

### ISSUE THREAD

**Issue by aenima-x** [myspaghetti/macos-virtualbox#215]
your script works perfect, but I'm trying to create an OVA from the created VM.
And when it boots I get and UEFI boot error.
All the settings are the same of the original VM.
You you have any idea of what could be the problem?

**Comment by myspaghetti** [comment]
If you've applied a CPU profile or CPUID to the VM on one machine and are running the VM on a different machine with a different CPU, the CPU profile won't match. If that's the case, please see the documentation about removing the CPU profile and CPUID.

Otherwise, the virtual disk image could have been damaged. To rule that out, copy the disk image from one device to another and run a checksum on each before starting the VM. You can apply the script on the new virtual machine by editing the script with the new VM's name and executing `./macos-guest-virtualbox.sh configure_vm` then attaching the verified-correct disk image as a SATA drive and starting the VM.

Otherwise, please take a screenshot of the boot error and attach it here, although if it's anything other than the CPU configuration or a corrupt disk image then I probably won't be able to troubleshoot it.

**Comment by myspaghetti** [comment]
...or, if by "UEFI boot error" you mean VirtualBox loads the EFI Internal Shell and waits for manual input, that's because the UUID of the boot device is modified when exporting to OVA. Manually boot macOS's `boot.efi` and it will update the NVRAM with the correct boot device UUID and boot normally.

`boot.efi` is usually located at `FSN:\System\Library\CoreServices\boot.efi` or at `FSN:\[UUID]\boot.efi` after a system update or on the recovery volume.

![EFI Internal Shell](https://user-images.githubusercontent.com/31696646/82796630-8012b900-9e7e-11ea-8c44-dfa31fc285f6.png)

**Comment by aenima-x** [comment]
Thanks @myspaghetti is the 2nd problem.
When Vbox converts the VM it doesn't include de nvram file.
If I replace the new nvram file with the original it boots fine
