### ISSUE TITLE
GUI: Aborting startup due to invalid machine state detected: 1

### ISSUE THREAD

**Issue by alnet82** [myspaghetti/macos-virtualbox#228]
Fail to start the VM during the install process.
Attaching troubleshoot.txt

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/4687309/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
Looks like the virtual machine was active for all of 5 milliseconds. First, remove the applied Intel Core i7-5600U CPU profile and any custom CPUID settings:
```
VBoxManage modifyvm "macOS" --cpu-profile host
VBoxManage modifyvm "macOS" --cpuidremoveall
```
Then try to start up the virtual machine. If you get the same error, try any of the following CPU profiles:
```
VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-2635QM"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-3960X"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i5-3570"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-5600U"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"
```
...actually we can rule out the i7-5600U because that's the one reported in the log. If each of the above profiles fails, you will have to specify a custom [CPUID](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport) that disables all the features that cause macOS to have a kernel panic.

**Comment by myspaghetti** [comment]
Scratch my (deleted) previous answer, searching for `Guru Meditation -79` shows that VirtualBox cannot start the VM because some other virtualization software is preventing VirtualBox from using the virtualization hardware.

**Comment by fastbootfinesse** [comment]
Was this ever resolved?

**Comment by myspaghetti** [comment]
This is an issue tracker for issues with the script, not for general issues with VirtualBox.
