### ISSUE TITLE
VirtualBox assigns 128 MB of video memory, however only 7MB is recognized

### ISSUE THREAD

**Issue by aidenmitchell** [myspaghetti/macos-virtualbox#244]
Can this be fixed? Thanks.

**Comment by myspaghetti** [comment]
macOS reports 3MB or 7MB of VRAM but I'm pretty sure it uses the entire 128MB, otherwise graphics performance would be even more degraded than it is. If you really care about how much VRAM is reported, you can switch to the VMSVGA virtual graphics device. You use [VMWare Tools](https://my.vmware.com/web/vmware/details?downloadGroup=VMTOOLS1106&productId=973) in conjunction with VMSVGA for ever-so-slightly better graphics performance, but you'll also have to install a bootloader to change the graphics resolution.

The difference is minor and in my opinion not worth the hassle.
