### ISSUE TITLE
Question: Two Values in iMessage Config

### ISSUE THREAD

**Issue by mstaragrieb** [myspaghetti/macos-virtualbox#265]
I have figured out most if it, but this has me puzzled.

I am unclear on these two values and where to find them.
DmiOEMVBoxVer="string:1"             # Apple ROM Info
DmiOEMVBoxRev="string:2"        # Apple ROM Info

I have looked all over for these values. When running "system_profiler SPHardwareDataType" I get these fields.
      Model Name: 
      Model Identifier: 
      Processor Name:
      Processor Speed: 
      Number of Processors: 
      Total Number of Cores: 
      L2 Cache (per Core):
      L3 Cache: 
      Hyper-Threading Technology: 
      Memory: 
      Boot ROM Version: 
      SMC Version (system): 
      Serial Number (system): 
      Hardware UUID: 

I believe SMC Version = DmiOEMVBoxVer

But I cannot figure out what the revision would be?

**Comment by myspaghetti** [comment]
These values are probably not required to connect to iMessage.

If they're not provided by a genuine Apple device then they are probably not checked when connecting to iMessage; I believe only the system serial, board serial (on EFI and NVRAM), ROM, and system ID are checked unless the activity is suspicious or already flagged.

If you do find it, "version" is left of the decimal and "revision" is the decimal and right of it.

If the Apple ROM info is `1.23456` then the values are as follows:
```
DmiOEMVBoxVer="string:1"
DmiOEMVBoxRev="string:.23456"
```
Prepending `string:` is required, otherwise VirtualBox might interpret the value as an integer or a float.

**Comment by mstaragrieb** [comment]
Thanks, that helps. I got everything else off of my macbook, and it still won't connect so I will keep futzing. Thanks for all the engagement. Do your have a patreon or something?

**Comment by myspaghetti** [comment]
>it still won't connect

Check the values on the VM the same way you check them on the genuine Mac. The three NVRAM parameters `MLB`, `ROM`, and `SYSTEM_UUID` need to be created or updated through the EFI Interactive Shell.

I don't have a Patreon, but thanks for asking. If I ever work on a major project I'd consider accepting donations.
