### ISSUE TITLE
Still happens.

### ISSUE THREAD

**Issue by snaildos** [myspaghetti/macos-virtualbox#282]
I checked all my WSL distro's and I have 2 docker WSL's (running on WSL2) so I deleted those, rebooted and the message STILL persists!

**Comment by myspaghetti** [comment]
This is an issue tracker for issues with the script. The script has correctly identified that VirtualBox is using NEM and that VT-x/AMD-V is not available for VirtualBox. By design the script does not require elevated privileges and does not alter any system configuration. No support is offered for disabling Hyper-V or core isolation or any of the many Windows features that prevent VirtualBox from using VT-x/AMD-V.
