### ISSUE TITLE
virtual machine platform prevents hardware virtualization

### ISSUE THREAD

**Issue by bjubes** [myspaghetti/macos-virtualbox#290]
"virtual machine platform" in windows features will prevent hardware supported virtualization. This should probably be added to the list of things logged out when this check fails since its counter-intuitive and was hard to diagnose.

**Comment by myspaghetti** [comment]
The list is not supposed to be exhaustive, there are even more unlikely features like "credential guard" that prevent VirtualBox from using VT-x/AMD-V. I don't intend to keep track of them. As far as counter-intuitive go, at least "virtual machine platform" has "virtual machine" in the name.

Oracle should keep a list of Windows features that disable VT-x-/AMD-V access instead of leaving the "documentation" effort for their hostile forum environment.
