### ISSUE TITLE
Failed to create "Catalina_BaseSystem.vdi

### ISSUE THREAD

**Issue by StewartPolsky** [myspaghetti/macos-virtualbox#295]
I had previously used the script and had a MacOS guest working. I was trying to use OpenCore and made a mess. No big deal. I deleted the VirtualMachine and ran the script again.

This time I receive an error:
Catalina_BaseSystem.dmg --> Catalina_BaseSystem.img

/cygdrive/f/Downloads/macos-guest-virtualbox.sh: line 310:   916 Segmentation fault      "${PWD%%/}/dmg2img.exe" "$@"
Converting from raw image file="Catalina_BaseSystem.img" to file="Catalina_BaseS
ystem.vdi"...
Creating dynamic image with size 0 bytes (0MB)...
VBoxManage.exe: error: Cannot create the disk image "Catalina_BaseSystem.vdi": V
ERR_INVALID_PARAMETER
Failed to create "Catalina_BaseSystem.vdi".
Exiting.

The script says it finds the previously downloaded files. I figured the files might be corrupt. I want to delete the files and have the script download them again however I can not find the files to delete.

Where does the script download the files to? What would be the next step to resolve this error? I read through the documentation but did not find the answer I am looking for.

Thank you

**Comment by StewartPolsky** [comment]
I was able to resolve my issue by deleting the previously downloaded MacOS files.
The downloaded files were in C:\cygwin64\home\%USERNAME%

**Comment by myspaghetti** [comment]
The script does resume downloads but it does not verify that the downloaded files actually need resuming. If there are existing files and the Apple server offers a new version of the files which is larger, the script appends the extra data to the existing files, which in your case caused the segmentation fault in `dmg2img`.

The correct solution is to parse the checksums provided by Apple, but unfortunately I could not find any documentation for the checksum files (`.chunklist` and `.integrityDataV1`) and I don't want to use third-party checksums so this bug is currently closed as `wontfix`
