### ISSUE TITLE
/sbin/newfs_hfs failed with error 256

### ISSUE THREAD

**Issue by benze** [myspaghetti/macos-virtualbox#351]
My host PC is a MacBook Pro 2011 running High Sierra (10.13.6) running on VirtualBox 6.1.16.  I previously failed to install Catalina so I tried to install High Sierra in the VM instead.  However, when I install the VM, I cannot get past the install/bootup sequence.

To start, it doesn't boot using my host CPU information.  I needed to use the `Intel Core i7-2635QM` profile to get the VM to boot up.
```
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-2635QM"
```

However, once it does boot up, it fails during the partitioning sequence:
![image](https://user-images.githubusercontent.com/2797306/101442271-0194da80-38e9-11eb-9f63-961166360f3d.png)

If I try to create the partition manually, the partition creation works fine, but rerunning the `bootinst.sh` still fails when trying to extract the filesystem:
![image](https://user-images.githubusercontent.com/2797306/101442518-79fb9b80-38e9-11eb-96d5-5d2e90c63abd.png)

Attached is the troubleshooting log 
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/5657002/macOS_troubleshoot.txt)

Any suggestions what I can try next?

**Comment by myspaghetti** [comment]
Hi! My lack of replies were due to investigating the issue! I'm running the script on a MacBook Pro 2011 with an Intel i5 2515M processor.

The `error 256` is definitely a CPUID issue, which causes memory corruption. You'll have to figure out which CPU instruction set needs to be disabled so macOS can run happily without corruption issues. The profile you chose is [almost identical to the MacBook Pro 2011 CPU](https://ark.intel.com/content/www/us/en/ark/compare.html?productIds=53449,53463) so if that doesn't work, you'll have to go into the weeds of [VirtualBox CPUID settings.](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport) While other virtualization software like QEMU offer really nice CPU instruction set options (`-cpu`), VirtualBox requires manually entering the [CPUID leaf bytes](https://en.wikipedia.org/wiki/CPUID).

No support is offered for CPUID settings, but incidentally I have the exact same device so I'll look into it a bit.

**Comment by myspaghetti** [comment]
Hi! My lack of replies were due to investigating the issue! I'm running the script on a MacBook Pro 2011 with an Intel i5 2515M processor.

The `error 256` is definitely a CPUID issue, which causes memory corruption. You'll have to figure out which CPU instruction set needs to be disabled so macOS can run happily without corruption issues. The profile you chose is identical to the MacBook Pro 2011 8,2 CPU so it's redundant and you can clear the CPU profile as described in the documentation.

Since it appears the CPU is not supported, you'll have to go into the weeds of [VirtualBox CPUID settings.](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport) While other virtualization software like QEMU offer really nice CPU instruction set options (`-cpu`), VirtualBox requires manually entering the [CPUID leaf bytes](https://en.wikipedia.org/wiki/CPUID).

No support is offered for CPUID settings, but incidentally I have a similar device so I'll look into it a bit.

**Comment by myspaghetti** [comment]
Hi! My lack of replies were due to investigating the issue! I'm running the script on a MacBook Pro 2011 with an Intel i5 2515M processor.

The `error 256` is either corrupt download issue or a CPUID issue, which causes memory corruption. You'll have to figure out which CPU instruction set needs to be disabled so macOS can run happily without corruption issues. The profile you chose is identical to the MacBook Pro 2011 8,2 CPU so it's redundant and you can clear the CPU profile as described in the documentation.

Since it appears the CPU is not supported, you'll have to go into the weeds of [VirtualBox CPUID settings.](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport) While other virtualization software like QEMU offer really nice CPU instruction set options (`-cpu`), VirtualBox requires manually entering the [CPUID leaf bytes](https://en.wikipedia.org/wiki/CPUID).

No support is offered for CPUID settings, but incidentally I have a similar device so I'll look into it a bit.

**Comment by myspaghetti** [comment]
I couldn't reproduce the issue on the MacBookPro8,1 (i5 2515M) which means that it's very likely the MacBookPro8,2 CPU (i7 2635QM) _is supported_ after all.

The `md5` checksum for `HighSierra_BaseSystem.dmg` on the provided log is correct too, so that's as much troubleshooting as I can offer.
