### ISSUE TITLE
installer script fails at 73%

### ISSUE THREAD

**Issue by andrewtoups** [myspaghetti/macos-virtualbox#365]
Seems to be the same problem as this issue: https://github.com/myspaghetti/macos-virtualbox/issues/360

However I redownloaded the install file from another machine since my windows desktop seems to have trouble downloading large files like this, I ran the script that breaks it into parts again, and it still fails at the exact same place.

Here is my troubleshoot file:

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/5761107/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report!

The installation files' checksums are correct so the issue is with macOS compatibility with the CPU. Unsupported CPUs cause memory corruption issues. I would guess recent versions of macOS are not compatible with a 2008 CPU.

See the documentation about either selecting a preconfigured VirtualBox CPU profile or [manually tweaking the VirtualBox CPUID settings.](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport)

The script does not check for CPU compatibility. The rationale for not implementing a fix is that keeping a database of compatible CPUs is beyond the humble scope of this script.
