### ISSUE TITLE
iMessage Help

### ISSUE THREAD

**Issue by sethjt33** [myspaghetti/macos-virtualbox#371]
I am out of ideas with iMessage and iCloud failing to allow me to sign in, or even create a new Apple ID.  MacOS installed and working great otherwise just no Apple services.  I would greatly appreciate any help in getting this working.  These are the variables I set in the script prior to executing.

[edited for privacy reasons - myspaghetti]

**Comment by myspaghetti** [comment]
You cannot create a new Apple ID without implementing SMC and NVRAM variables than the script does not provide. However, you _can_ log in if you provide genuine or genuine-like Mac parameters as specified in the script.

You accidentally  set the `MLB` variable to `"${XXXXXXXXXXXXXXXXX}"` where the dollar sign, open curly bracket close curly bracket `${}` should not be used, it should be just `XXXXXXXXXXXXXXXXX` or `MLB="${DmiBoardSerial}"` since the `MLB` variable is supposed to be identical to the `DmiBoardSerial` variable.

Since you already booted the virtual machine with the wrong `MLB` value you will need to delete the NVRAM file and re-apply the NVRAM parameters as specified in the documentation under the section `Changing the EFI and NVRAM parameters after installation`

**Comment by sethjt33** [comment]
Well as you can surly tell, I am a idiot!  This did seem to make things better but now I am getting the message: "You cannot sign in to iMessage on this Mac at this time. To use iMessage with this Mac, contact Apple Support and provide the code below.  Customer Code: 2699:8019:9256"

Can you help with this?

**Comment by myspaghetti** [comment]
If you've used information from a Mac you own, I suggest calling Apple and explaining the situation, they will un-flag your Apple ID with a push of a button. There are even reports on the internet of Apple being helpful enough to un-flag your Apple ID if you own *any* Apple device, even if it's not a Mac.

After that, you need to avoid logging in with the genuine details on two machines at the same time so Apple's systems won't flag it for suspicious activity.

**Comment by myspaghetti** [comment]
If you've used information from a Mac you own, I suggest calling Apple and explaining the situation, they will un-flag your Apple ID with a push of a button. There are even [reports on the internet](https://www.google.com/search?hl=en&q=Mac+PlatformInfo) of Apple being helpful enough to un-flag your Apple ID if you own *any* Apple device, even if it's not a Mac.

After that, you need to avoid logging in with the genuine details on two machines at the same time so Apple's systems won't flag it for suspicious activity.

**Comment by sethjt33** [comment]
Can you explain to me how to copy the generated files to the macOS EFI System Partition?

**Comment by myspaghetti** [comment]
>is there a way to copy files to the macOS EFI System Partition from the host side?

Yes, if the host system can mount the VDI or VMDK file, but since the documentation already describes how to do it through the guest you'd probably save time doing it through the guest. It's even possible to edit the NVRAM directly from the host, but it's probably easier to erase the NVRAM file on the host and supply new values through the guest.

>the instructions read like the VM should be shutdown

Correct, after mounting the ESP in the guest and copying the NVRAM files and startup script, the guest needs to be shut down or restarted and booted into the EFI Internal Shell. Then the `startup.nsh` file that was copied to the ESP is executed, which loads up the NVRAM values from the NVRAM files that were copied. Then macOS boots, reads the new NVRAM values, writes some new NVRAM values of its own. Hopefully if the NVRAM was deleted as specified there won't be any conflicts and you'd be able to use existing Apple IDs on the virtual machine (but not register new Apple IDs because the required SMC and NVRAM values are not provided by the script, but you could provide them with OpenCore - for which no support is offered)

**Comment by sethjt33** [comment]
It was exhausting but it is finally working now with iMessage! After taking away the ${} and calling apple, waiting well over 24hrs for them to figure it out on their end, it is now working!  Thank you very much for your help.
