### ISSUE TITLE
Opencore

### ISSUE THREAD

**Issue by 1333481** [myspaghetti/macos-virtualbox#400]
Could you point me to a guide to install opencore after installing the os to the vm?

**Comment by myspaghetti** [comment]
OpenCore [cautions against using any guide except the official specification](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) due to "unavoidable obsolescence". Almost every new version of OpenCore breaks compatibility with its old configuration files. OpenCore development moves so fast that by the time a guide is released, it's already incompatible with the latest version. That said, [Dortania seems to be keeping an up-to-date OpenCore guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/opencore-efi.html).

For the very basic boot functionality you put the `OpenCore.efi` and `config.plist` files in the ESP partition path `/EFI/OC/` and add the line `load fs0:\EFI\OC\OpencCore.efi` to the VirtualBox EFI Internal Shell `startup.nsh` file or execute it manually. From there on I suggest you get intimately familiar with the official documentation.

I took a look at OpenCore 0.6.6 and per usual it has amazing new features.
