### ISSUE TITLE
How to run the script successfully on windows

### ISSUE THREAD

**Issue by peerliss** [myspaghetti/macos-virtualbox#426]
I have installed virtualbox and the extension pack, after pressing enter the second time to review the script configiration the prompt suddenly closes. I have also tried to run the documentation and troubleshoot functions using the command prompt and a virtualbox bash window very briefly opens up and closes. Is there anything I'm missing in order to get this working?

**Comment by myspaghetti** [comment]
Seems like `bash` (`mintty.exe` / Cygwin Terminal) is running non-interactively. Run the default Cygwin Terminal shortcut or run `mintty.exe` with the `--hold always` option or make sure bash is running interactively with the `-i` option.

By default the script inherits the environment's interactive option, because the script can be run interactively or non-interactively. Maybe it should be interactive by default because advanced users who want to run it non-interactively will know how to do that.

**Comment by peerliss** [comment]
It worked after running the script using Cygwin and installing the required patches, previously I was trying to install it using the windows command prompt. Thanks for your help.
