### ISSUE TITLE
Getting error Hyper-V error when running script.

### ISSUE THREAD

**Issue by accurateisaiah** [myspaghetti/macos-virtualbox#440]
I'm trying to run the script and I get this error:
`Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
Exiting.`

Hyper-V and Windows Sandbox are disabled! Why is this happening?

**Comment by myspaghetti** [comment]
There are many Windows features and other software that disable VT-x/AMD-V access for VirtualBox. Core Isolation, Credential Guard, Device Guard, some virtualization software, and even some anti-virus software block VirtualBox from accessing VT-x/AMD-V. The script does not provide an exhaustive list of all software that blocks VirtualBox, and VirtualBox doesn't (and probably can't) specify which software is blocking it, so troubleshooting this issue is up to you. People have reported that running the following command as administrator and rebooting twice usually solves the issue:
```
bcdedit /set hypervisorlaunchtype off 
```

**Comment by redstreet** [comment]
See #398 for reference links @accurateisaiah

**Comment by Merculous** [comment]
Using the command above definitely fixed this issue.
