### ISSUE TITLE
Virtualbox error during populate_bootable_installer_virtual_disk

### ISSUE THREAD

**Issue by jaddison06** [myspaghetti/macos-virtualbox#441]
The script moves on to the populate_bootable_installer_virtual_disk stage. A Virtualbox window opens and then closes straight away. Obviously the VM is trying to boot but it can't. If I try to boot it manually from VB I get this message:

![image](https://user-images.githubusercontent.com/64211121/114280455-32208880-9a31-11eb-8d54-e0adb624464c.png)

I'm on Pop!OS 20.10 with Virtualbox 6.1.16

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report!

Please run `./macos-guest-virtualbox.sh` and attach the resulting `.txt` file here.

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report!

Please run `./macos-guest-virtualbox.sh troubleshoot` and attach the resulting `.txt` file here.

**Comment by jaddison06** [comment]
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6291525/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
Unrelated to the boot issue, seems like the file `InstallESDDmg.pkg` did not finish downloading properly. This doesn't explain why VirtualBox won't boot, but it does require fixing (by resuming the download) in order for the script to complete successfully.

These are the correct md5 sums for the downloaded files:
```
 363aafb01775d361c3c95a3b4540e44f *Catalina_BaseSystem.chunklist
e8b106cc85ac71f2eb2fe2e4eb62357c *Catalina_BaseSystem.dmg
c39544720166ae77fd4795340c166289 *Catalina_InstallESDDmg.pkg
81d00dfb92442baad965fdfba77e4d92 *Catalina_InstallInfo.plist
422384c9eb4d599f2dd4e8f0b62c31d9 *Catalina_AppleDiagnostics.chunklist
b03b3beaa4db7dbee013f45d94096842 *Catalina_AppleDiagnostics.dmg
```

And for the split-for-ISO-compatibility `InstallESDDmg.pkg` file:
```
37f6018df93ece4a57a7ddffad1edf2b *Catalina_InstallESD.part00
bd88dccae42d172c5f853e7c90d392bf *Catalina_InstallESD.part01
7797b9b9155e6fe36f1c913a1332cb1e *Catalina_InstallESD.part02
8fc9fff5b3da0caa1d58dba49ba782d9 *Catalina_InstallESD.part03
183bee8a87c8ed75188cc2904e55d9d6 *Catalina_InstallESD.part04
d97a3411ff914786a28cfb09de964a38 *Catalina_InstallESD.part05
72e32b668be86afcda65a07818f73c64 *Catalina_InstallESD.part06
fbb62a5a148c3ffb567f9d99ff1cf11d *Catalina_InstallESD.part07
```

Now what *is* causing VirtualBox is a lot of misconfigurations. The firmware is set to BIOS (supposed to be UEFI), the number of CPU cores is set to 1 (supposed to be 2), RAM is set to 128MB (supposed to be at least 2048, 4096 by default), etc etc.

Seems quite a few of the settings have been misconfigured, manually I assume. I'm removing the "bug" label as this error is not caused by the script.

**Comment by jaddison06** [comment]
I didn't change any of this manually - the only part of the script I changed was the CPU count, from 2 -> 4. I'll try redownloading but I'm not sure where those misconfigurations came from...

**Comment by myspaghetti** [comment]
Sorry, I was too hasty and jumped to conclusions. Perhaps the script stage `configure_vm` failed to run.

**Comment by jaddison06** [comment]
Honestly I've got no idea - I don't often work with Virtualbox. I'll let you know once the download has completed & i guess we'll see if the problem happens again

**Comment by myspaghetti** [comment]
I've added a check to [version 0.98.4](https://github.com/myspaghetti/macos-virtualbox/commit/28e75d5431e495a04065fa6b469ee2405be20394) that exits the script with an error message if the script fails to configure the VM.

**Comment by jaddison06** [comment]
It's working now - previously it looks like the download failed at about 40% but the script just kept running. Makes sense to verify before continuing. Thanks for your help!

**Comment by myspaghetti** [comment]
Again I apologize for jumping to conclusions.
