### ISSUE TITLE
Command Line Support And Auto Install Additions

### ISSUE THREAD

**Issue by cheznewa** [myspaghetti/macos-virtualbox#443]
Hello, Is Possible To Add The Command Line Instead Edit The Script File?
And Is Possible To Add Auto Installation VirtualBox Guest Additions During/After Installation?

Newa Our Master.

**Comment by myspaghetti** [comment]
The script by design does not modify any configuration on the host system and does not use elevated privileges. Since installing software almost always requires administrative privileges, a feature like installing VirtualBox addons will not be implemented. It is possible to configure the script using an external file by copying the contents of the `configure_vm` function, editing the appropriate variable assignment lines, and having the script load the configuration by exporting the `macos_vm_vars_file` variable:

```
export macos_vm_vars_file=/path/to/variable_assignment_file
```
