### ISSUE TITLE
Big Sur support

### ISSUE THREAD

**Issue by mehyaa** [myspaghetti/macos-virtualbox#453]
Hi, great work 👍🏻

Do you plan to add Big Sur support to the script?

**Comment by myspaghetti** [comment]
Thanks. Regarding Big Sur please see [issue 254](https://github.com/myspaghetti/macos-virtualbox/issues/254#issuecomment-750889854). Implementing this requires `xar` which is only available from source, so at the moment installing Big Sur from scratch is not supported. However, upgrading to Big Sur is extremely easy and can be done unattended in less than an hour (depending on your download speed).

**Comment by tuxpeople** [comment]
@myspaghetti Jack, would you mind to further elaborate "can be done unattended in less than an hour"? I'm interested in the workflow.

I'm aware of `softwareupdate --fetch-full-installer` to automatically download the installer on macos. Would step 2 be something like `'/Applications/Install macOS Big Sur.app/Contents/Resources/startosinstall' --agreetolicense --forcequitapps`? Can one somehow enter those commands from the host directly into the VM for doing it in a script?

**Comment by myspaghetti** [comment]
The graphical version of Software Update does all the work with a few clicks, and since you have graphical access to the VM, that's what I meant about unattended.

For a terminal-based approach, `softwareupdate --fetch-full-installer` is [considered unreliable](https://www.jamf.com/blog/reinstall-a-clean-macos-with-one-button/) [jamf.com], see [this discussion of fleet deployment strategies](https://scriptingosx.com/2020/11/deploying-the-big-sur-installer-application/) [scriptingosx.com]. Creating a bootable installer seems like [the thing to do for fleets](https://twocanoes.com/products/mac/mac-deploy-stick/) [twocanoes.com], but for a VM surely it's faster and easier to use Software Update and then clone the VM as many times as you want.

>Can one somehow enter those commands from the host directly into the VM for doing it in a script?

Yes, you can see my horrific implementation of `VBoxManage keyboardputscancode` in the script [or here](https://github.com/myspaghetti/virtualbox-scancodes/blob/master/scancodes.sh), or you could enable SSH on the guest macOS for a not-convoluted approach.

**Comment by tuxpeople** [comment]
@myspaghetti Jack, thanks a lot! In my tests, I always got an installer with `softwareupdate --fetch-full-installer` so it's either me being lucky or they made it more reliable.
