### ISSUE TITLE
DmiOEMVBoxVer & DmiOEMVBoxRev

### ISSUE THREAD

**Issue by mehyaa** [myspaghetti/macos-virtualbox#456]
After the latest commits `DmiOEMVBoxVer` and `DmiOEMVBoxRev` variables is not set as default. What should I set them to? I'm trying to emualate and generate `Macmini7,1` hardware info.

**Comment by myspaghetti** [comment]
As far as I can tell they are not required to log in to iMessage/iCloud with an existing active account, so I removed them after a few users couldn't find the required values on their genuine Mac devices.

If you need them for the sake of complete emulation you're still far off because there are quite a lot of [NVRAM parameters](https://github.com/erikberglund/AppleNVRAM/blob/df3514418a8b3782d252412961e8e40366b8303b/All/README.md) and EFI parameters and SMC parameters that are not provided by VirtualBox or the script and require far more digging and a more complete solution like OpenCore.

If you just want them for iMessage you don't need them. They default to some VirtualBox preset value which iMessage doesn't care about.

**Comment by myspaghetti** [comment]
Yeah, same answer. I think the App Store has even less checks than iMessage. Maybe no checks at all.
