### ISSUE TITLE
Virtual HD outside of the VM directory

### ISSUE THREAD

**Issue by tuxpeople** [myspaghetti/macos-virtualbox#474]
Hi

Not sure if this is to be considered as a "bug". I used the script on BigSur 11.4 (20F71) to create a VM. The script created the VM successfully in my default location of Virtual Box VMs: `~/VirtualBox VMs/macOS/`. But not the HDD-File, which got created in the directory where I called the script from, which happens to be my homedir:

```
$ file ~/macOS.vdi
/Users/myuser/macOS.vdi: VirtualBox Disk Image, major 1, minor 1 (<<< Oracle VM VirtualBox Disk Image >>>), 83886080000 bytes
```

Sure, I can move it manually and I did not test yet if it always gets created where the script runs or always in my home. But it would be nicer if the HDD-File is also in the directory of the VM.

**Comment by myspaghetti** [comment]
Hi! It's not a bug, it's a feature... Sorry!

On some systems VirtualBox may be running with different permissions than the script, and it might be that the script user privileges don't include read/write access to the VirtualBox VM directory.

The script by design is run without elevated (admin, superuser, root) privileges and by design creates and modifies files only on the working directory.
