### ISSUE TITLE
i installed fine, but after shutting down , no option to boot Mac from virtual box 

### ISSUE THREAD

**Issue by metitarvel** [myspaghetti/macos-virtualbox#481]
also im a total newb and cant figure out how to change the amount of ram assigned.
was running very smooth in debian 10 ..

followed the script was a clean install ... played around with it everything worked well.

i shut down . and went back in to virtual box expecting to be able to see "macos" to be able to start it like any of my other VM'S and nothing is there . i tryed adding the VDI from where i installed in my directory and it booted to startup.nsh 

any help would be great as im new to linux 

metitarvel@mail.ru

**Comment by myspaghetti** [comment]
You might have installed the VM with elevated privileges and now the non-elevated VirtualBox doesn't have read permissions for the `.vbox` file. At any rate if you manually create a virtual machine and attach the working `macOS.vdi` all you have to do is run `./macos-guest-virtualbox.sh configure_vm` and it will be configured correctly. Then `startup.nsh` will be able to call the macOS boot process.

**Comment by metitarvel** [comment]
this sounds about right as when i ran the original script i did it with sudo, when you say "manually create a virtual machine and attach the working macOS.vdi all you have to do is run ./macos-guest-virtualbox.sh configure_vm"

where it says ./macos-guest-virtualbox.sh configure_vm"  would "configure_vm" be the name of the vdi as in macOS or literally configure_vm, thank you for replying so quickly and thank you for making this script as ive tried multiple other ways and this has been the only working one i could find.

**Comment by metitarvel** [comment]
i believe you are absolutely correct from my little knowledge of linux, i just ran sudo virtualbox in terminal and bingo it shows mac osx running. although my other VM's are not shown in the vbox manager i assume thats because i i didnt install them with escalated privileges.
in future for when i install this on my other thinkpad, how do install the script without escalated privileges. as when i intially tried to install the script in terminal it said permission denied. 

sorry for all the questions..
one more thing how do i i assign more ram to this machine ! its only running on the default 2GB

**Comment by myspaghetti** [comment]
* `./macos-guest-virtualbox.sh configure_vm` is the command as typed into the host (Linux) terminal, the name of the VM needs to be edited into the script on line `18`, replace `macOS` on that line with the name of the VM, or keep the default name `macOS`
* `startup.nsh` does not need to be edited if the script installed it. If the script didn't install it (due to a failure at the last stage which sometimes happens), booting the VM will drop to the EFI Internal Shell and you will need to boot manually once, after which macOS sets the correct boot parameters in the NVRAM. The command to boot manually is `fs1:\System\Library\CoreServices\boot.efi` or fs2 or fs3 or fs4 or fs5 depending on what VirtualBox decided to number the filesystem of the macOS boot partition. Then you can manually install `startup.nsh` as specified in the documentation if required, but it usually isn't on VirtualBox 6 and higher.
* RAM can be assigned manually on the VirtualBox GUI under Settings > System > Base Memory, or it can be set through the terminal with `VBoxManage modifyvm "macOS" --memory <MEMORY SIZE IN MEGABIBYTES>`, for example `VBoxManage modifyvm "macOS" --memory 8192`
* The virtual discs on the macOS guest are safe to eject, and they can even be deleted automatically if the VM is powered off and the following command is run in the host terminal: `./macos-guest-virtualbox.sh delete_temporary_files`

I'm fine with beginner questions as long as they are about the script. Sometimes people post "how do I run an interactive bash shell" and that's a little too fundamental to be asking here. Finally, questions like "how do I export the virtual machine to QEMU/KVM" are a little too advanced to be asked here, but [there are guides that walk through it](https://www.nicksherlock.com/2020/06/installing-macos-big-sur-on-proxmox/) and if you already have a working macOS VMDK you can skip the installation media creation and attach the working VMDK to get quicker results.
