### ISSUE TITLE
I got everything to work... except the mouse is VERY slow

### ISSUE THREAD

**Issue by ImNotRice** [myspaghetti/macos-virtualbox#504]
I'm at my wit's end. I tried so much I can't even list everything I did. Windows 10 Host, Catalina Guest.

I remember installing Guest Extension Pack, fiddling with the USB Controller, Graphics Controller, acceleration, pointing devices, changing extended features, changing resolutions, tried CPU counts from 1-8. Tried RAM values from 2048-8192.

Playing video is smooth. However, when I start moving my mouse, videos start to drop to less than 1 FPS, and only when I stop moving the cursor does the Mac return to being smooth.

**Comment by ImNotRice** [comment]
Looks like I can't get it to run smoothly. The script works well, I'm pretty sure this is a VirtualBox problem. I'm on Windows 10, so I guess VMWare is my best option. Is there support for porting the installation over to VMWare? Or is that something I need to figure out myself. Thanks!

**Comment by myspaghetti** [comment]
There's no support but VMWare can run macOS by default, so simply booting a bootable macOS VMDK should work. I'm going to leave the issue open for a few more days in case anybody provides further information.

**Comment by atiyabzafar** [comment]
I've encountered similar problem and done the same things. The cursor is too slow and lags always.

Is there a way for me to use same image. Or copy the same image to VM ware to confirm if it's a virtual box issue.

**Comment by myspaghetti** [comment]
Yes, you can convert the VDI to a VMDK or a raw disk image with [`VBoxManage clonemedium`](https://www.virtualbox.org/manual/ch08.html#vboxmanage-clonemedium) and boot it through VMWare, or you can configure OpenCore and boot it through QEMU/KVM. [This tutorial](https://www.nicksherlock.com/2020/06/installing-macos-big-sur-on-proxmox/) describes how to create a VM from scratch. The configuration for an existing disk image is the same, except instead of a bootable installer you're booting an existing installed system. You can save time by configuring OpenCore on the guest's EFI System Partition while it's still on VirtualBox, and when it's working convert it and boot it on QEMU/KVM.

I expect that [as Intel virtual GPU passthrough matures](https://wiki.archlinux.org/title/Intel_GVT-g) QEMU/KVM with Intel GVT-g is going to be more accessible, saving time for people who want near-native macOS graphics performance.

**Comment by vinxenz** [comment]
Settings USB choose  "Controller USB 2.0 (OHCI + EHCI)"

**Comment by ImNotRice** [comment]
> Settings USB choose "Controller USB 2.0 (OHCI + EHCI)"

Tried all 3. None worked, unfortunately.

**Comment by myspaghetti** [comment]
Alright, we're at the point where people are just repeating wild stabs in the dark despite the submitter specifically saying they already tried that. Closing until substantial information is provided.
