### ISSUE TITLE
wsl与VirtrualBox不能同时运行

### ISSUE THREAD

**Issue by l376950095** [myspaghetti/macos-virtualbox#506]
我尝试在Windows 10下安装运行，运行wsl需要启用Hyper-V，但是启动Hyper-V后VirtrualBox虚拟机将无法运行，禁用Hyper-V后VirtrualBox正常，但wsl将无法运行。

**Comment by myspaghetti** [comment]
Hyper-V is required for WSL2. This script is only compatible with WSL, not WSL2. Microsoft really should have retroactively renamed WSL to WSL1.

Currently, you can either run the script on Windows on either Cygwin or WSL "1".

When nested-virtualization arrives in WSL2 on the Windows 10 Release (with a capital R) release, WSL and Cygwin will be deprecated and the new version of the script will only support macOS, Linux, and WSL2 with nested virtualization. The old version will still be available on the github release page but it will not be supported.

**Comment by l376950095** [comment]
> Hyper-V is required for WSL2. This script is only compatible with WSL, not WSL2. Microsoft really should have retroactively renamed WSL to WSL1.
> 
> Currently, you can either run the script on Windows on either Cygwin or WSL "1".
> 
> When nested-virtualization arrives in WSL2 on the Windows 10 Release (with a capital R) release, WSL and Cygwin will be deprecated and the new version of the script will only support macOS, Linux, and WSL2 with nested virtualization. The old version will still be available on the github release page but it will not be supported.

十分感谢，已通过Cygwin完成安装。

**Comment by MaidongAndYida** [comment]
@l376950095 请问你安装成功了吗？有博客记录安装过程吗？我学下咋安装的

**Comment by l376950095** [comment]
没安装成功，后面又遇到个bug，折腾起来就比较麻烦了，就没再弄。&nbsp;

&nbsp; &nbsp;梁超
&nbsp; &nbsp; TEL:18599038090
***@***.***
ADDR:新疆乌鲁木齐水磨沟区南湖南路中华保险一楼信息部


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月2日(星期一) 中午1:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [myspaghetti/macos-virtualbox] wsl与VirtrualBox不能同时运行 (#506)





 
@l376950095 请问你安装成功了吗？有博客记录安装过程吗？我学下咋安装的

**Comment by MaidongAndYida** [comment]
哦哦，谢谢回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myspaghetti/macos-virtualbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [myspaghetti/macos-virtualbox] wsl与VirtrualBox不能同时运行 (#506)





 没安装成功，后面又遇到个bug，折腾起来就比较麻烦了，就没再弄。&amp;nbsp; 
 
 &amp;nbsp; &amp;nbsp;梁超 
 &amp;nbsp; &amp;nbsp; TEL:18599038090 
 ***@***.*** 
 ADDR:新疆乌鲁木齐水磨沟区南湖南路中华保险一楼信息部 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年8月2日(星期一) 中午1:49 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [myspaghetti/macos-virtualbox] wsl与VirtrualBox不能同时运行 (#506) 
 
 
 
 
 
   
 @l376950095 请问你安装成功了吗？有博客记录安装过程吗？我学下咋安装的 
   
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
