### ISSUE TITLE
No Clue on how to run

### ISSUE THREAD

**Issue by Dividedby0KSJ** [myspaghetti/macos-virtualbox#510]
Ok, forgive me but i have NEVER used bash or any type of Linux type of code.
I have bash from installing GitHub on my PC, but I have no clue how to install the dependencies needed with bash.
I have tried looking for videos on how to use your wonderful program but found none.

pleas, can I have a step by step guide for how to use this on a Win10 PC with an AMD processor for someone that is stupid and doesn't know how to use bash or Linux.

I'm sorry.

**Comment by myspaghetti** [comment]
0. Git-Bash is not bash. Yes, the name is confusing, but Git-Bash is a git shell that is similar to bash, not a bash shell
1. Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads) (with or without Extension Pack)
2. Install [Cygwin](https://cygwin.com/install.html) with `coreutils`  `bash` `gzip`  `unzip`  `wget` and `xxd` selected from the full package list
3. Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
4. Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`./macos-guest-virtualbox.sh`)

Since you will execute the script on Windows 10 device with an AMD processor you will probably run into the following issues:

1. If the script reports `Virtualbox is not using hardware-supported virtualization features` then Hyper-V or a feature that uses it might be enabled, which blocks VirtualBox access to AMD-V. See [issue 440](https://github.com/myspaghetti/macos-virtualbox/issues/440).
2. If the guest boot hangs on `LoadKernelFromStream`, `EndRandomSeed`, or `EXITBS`, or if the installer reports it's corrupt or if it fails at 77%, this is likely a CPU issue. See the documentation command for workarounds. If none of the six CPU profiles work, try [this recommendation in issue 503](https://github.com/myspaghetti/macos-virtualbox/issues/503). If you want a more detailed explanation for the CPU ID, see the [writeup by Hayden Barnes](https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/) on the topic, particularly the [CPUID line](https://pastebin.ubuntu.com/p/GqHbMQSN99/). I don't know how to translate CPUID mnemonics to CPUID leaves, but if anyone wants to take a stab, that would be the repository's official CPUID recommendation.
