### ISSUE TITLE
BigSur boot

### ISSUE THREAD

**Issue by adiantek** [myspaghetti/macos-virtualbox#524]
Hi,

I installed catalina, upgraded to Big Sur. After shut down and start I see macOS Utilities (recovery):
![image](https://user-images.githubusercontent.com/13407885/130551319-8df9ea64-6417-4649-9b13-f9de14fcb245.png)

I must click "Startup disk" and select "macOS - Data" to run MacOS BigSur. How can I change to automatically and always boot "macOS - Data"?
![image](https://user-images.githubusercontent.com/13407885/130551432-4a34e15a-205e-4029-a8d9-972565a81202.png)

**Comment by myspaghetti** [comment]
You can change the boot disk in any of these ways:

* [Change the startup disk in Apple menu > System Preferences > Startup Disk](https://support.apple.com/en-us/guide/mac-help/mchlp1034/mac).
* [Press [Option] (⌥) or [Alt] on startup to get to the boot selection screen](https://support.apple.com/en-us/HT201255), then hold down (I think) [Ctrl] and press [Enter] to set the desired boot disk.
* Eject the macOS Base System from the VirtualBox virtual machine so the boot sequence skips it.
* If you're using VirtualBox 5.2, press [Esc] when the virtual machine powers up, boot the EFI Internal Shell, and edit `startup.nsh` so it points to the desired `boot.efi` file. This also works on newer versions of VirtualBox if the NVRAM points to the wrong `efi` boot file.

You only need to perform one of these.

**Comment by adiantek** [comment]
1) I had it before:
![image](https://user-images.githubusercontent.com/13407885/130694530-868ad051-f728-46a4-bcbb-4f92883819a5.png)
3) I removed Catalina_bootable_installer.vdi and got panic from MacOS
![image](https://user-images.githubusercontent.com/13407885/130695431-c8106069-6977-4037-89cb-da42ac6e6ffe.png)
4) There is my startup.nsh - what I should change?
![image](https://user-images.githubusercontent.com/13407885/130698019-253e24b6-d8c2-43e5-9dab-096defc6988a.png)
and run `fs5:\System\Library\CoreServices\boot.efi`:
![image](https://user-images.githubusercontent.com/13407885/130698111-292d12c7-84a1-4e4b-9af6-fdcd1acdcb44.png)
it's the same crash which I got when I removed Catalina_bootable_installer.vdi.

**Comment by myspaghetti** [comment]
Since Big Sur boots with the Catalina installer disk attached but fails if it's the only disk, the problem is definitely minor and probably somewhere in `com.apple.Boot.plist`. However if you don't feel like delving into macOS boot internals, you can try:

* Permanently attaching an empty HFS disk so Big Sur is the second disk again.
* Keeping the installer attached and editing the second and third `run (1 5)` to `run (2 5)` or `run (3 5)` so it skips the first one or two disks (I can't remember if the installer has an EFI partition; I think it doesn't so you only need to skip one partition in the EFI Internal Shell).

The proper solution would be fixing Big Sur's boot settings, or, if the VM has nothing on it, deleting the VM and making a new one, then upgrading to Big Sur when it's the *only* attached bootable disk so the boot sequence doesn't get complicated. I'd even suggest attaching a new, empty disk and installing Big Sur onto it, so you can keep the old, working macOS too.

**Comment by myspaghetti** [comment]
Since Big Sur boots with the Catalina installer disk attached but fails if it's the only disk, the problem is definitely minor and probably somewhere in `com.apple.Boot.plist`. However if you don't feel like delving into macOS boot internals, you can try:

* Permanently attaching an empty HFS disk so Big Sur is the second disk again.
* Keeping the installer attached and editing the second and third `run (1 5)` to `run (2 5)` or `run (3 5)` so it skips the first one or two disks (I can't remember if the installer has an EFI partition; I think it doesn't so you only need to skip one partition in the EFI Internal Shell).

The proper solution would be fixing Big Sur's boot settings, or, if the VM has nothing on it, deleting the VM and making a new one, then upgrading to Big Sur when it's the *only* attached bootable disk so the boot sequence doesn't get complicated. Another way, if you still have the Big Sur installer on the disk, is manually creating another 12GB virtual disk and [creating a Big Sur installer](https://support.apple.com/en-us/HT201372) on it, then using that installer to fix the boot sequence.

Again, the problem is probably very minor and I'm giving these hacky solutions so I don't have to look into `com.apple.Boot.plist`, but it's probably the source of the issue and it's probably very simple to fix it.
