### ISSUE TITLE
Error: -69888: Couldn't unmount disk when installing Catalina

### ISSUE THREAD

**Issue by harmtemolder** [myspaghetti/macos-virtualbox#530]
In the `populate_bootable_installer_virtual_disk` stage the `/Volumes/bootinst-sh/bootinst.sh` command in the Terminal results in the following:

```shell
Started partitioning on disk0
Unmounting disk
Error: -69888: Couldn't unmount disk
```

I found a reference to a deleted issue (#128) in #173 that mentions that same error, but nothing to solve it. What can I do to fix this?

Edit: I'm now trying `HighSierra` instead of `Catalina` and it looks like that one is working.

**Comment by myspaghetti** [comment]
I believe issue 128 was deleted after I couldn't reproduce the bug and the submitter didn't provide further information. I'll keep investigating this issue but currently I have no real direction for it.

**Comment by harmtemolder** [comment]
OK, no worries. I'm running High Sierra now without any problems, so not sure what the issue with Catalina is...

**Comment by Mechaniquake** [comment]
This happens when the installation is exited during **function populate_basesystem_virtual_disk()** 

When the script is creating disk partitions and the machine pauses because of "low disk space" errors on VB: switching off the VM and restarting from the above function works up to the script again. Then the error occurs.

The **disk0** partition looks like it stores GPT JHFS+ (macOS_bootinst[.]txt shows it uses diskutil ) and probably can't be unmounted for that reason.
