### ISSUE TITLE
safe to keep using original apple hardware after `set_variables()`?

### ISSUE THREAD

**Issue by mkarikom** [myspaghetti/macos-virtualbox#551]
#### Question:
Can I continue update, use iCloud, etc on the original host after running `get_parameters_from_macOS_host="yes"` on that machine?  In particular, does iCloud, the AppStore, etc care if the same hardware parameters (`DmiSystemSerial`, `DmiBoardSerial`, etc) are simultaneously being used at two IP addresses?

#### Background:
Note, `myWorkingMacbook` is  
My proposed use case is:
1. run `set_variables()` on `myWorkingMacbook` -> `myOsxGuest.vdi`
2. transfer `myOsxGuest.vdi` from `myWorkingMacbook` to `myHostPC` (a workstation running Ubuntu 20.04)
3. use iCloud-based services and perform MacOS updates on both `myWorkingMacbook` and `myOsxGuest`

**Comment by mkarikom** [comment]
Also, sincere thanks for your work on this script!

If the above use case is not advised, I'm fine obtaining a second Apple machine to harvest the device numbers, then retiring it after generating the VM.

**Comment by myspaghetti** [comment]
You're welcome. Some people have reported a "Call customer support" message when using iMessage with the same NVRAM and EFI parameters on two machines (virtual and physical). When initially testing the script I got this message and I had to call Apple to get my Apple ID cleared. It only takes a minute to fix but it's probably better not to chance it.

You can avoid it by [generating genuine-like parameters](https://github.com/corpnewt/GenSMBIOS).

I recommend, since you're using Ubuntu, installing OpenCore on the VM ([or using a preconfigured OpenCore image from OSX-KVM](https://github.com/kholia/OSX-KVM)) and then booting the macOS disk image with OpenCore on QEMU/KVM. You might want to convert the VDI to qcow2 to avoid any compatibility issues. The VM should boot as-is with the preconfigured OpenCore with mild edits to the [preconfigured QEMU command line options](https://github.com/kholia/OSX-KVM/blob/master/OpenCore-Boot.sh) (changing the disk image filename, removing the BaseSystem image). You'll have to configure OpenCore with the NVRAM and EFI parameters you want to use, there are [guides for configuring OpenCore](https://dortania.github.io/OpenCore-Install-Guide/).

The reason I'm writing all this is since you're already using Linux so you might as well use QEMU/KVM for far better performance than VirtualBox. Unless, of course, you just need something quick and dirty, in which case this script and VirtualBox are fine.

I offer no support for OpenCore, QEMU, or OSX-KVM, but I do recommend all three.

**Comment by mkarikom** [comment]
Thank you so much for these suggestions.  This short primer was exactly what I [didn't know] I needed.
