### ISSUE TITLE
The MacOS virtual machine doesn't appear in the manager

### ISSUE THREAD

**Issue by ding0z** [myspaghetti/macos-virtualbox#592]
Hi,
I successfully installed MacOs on Virtualbox but after that, the VM doesn't appear in the manager.
I'm trying now to reinstall it (screenshot).

Any thoughts?
Many thanks.

![Screenshot 2022-03-20 at 20 48 03](https://user-images.githubusercontent.com/59647128/159185416-d48a175d-3174-4527-927d-ecb5d838b1f0.JPG)

**Comment by myspaghetti** [comment]
This usually happens when the script is run with elevated priviledges (with `sudo` or the `root` user for example) and then when VirtualBox GUI is launched from a different user it cannot access the VM. If that's the case, move the VM disk image from its elevated-privileges location to a user-accessible location, then manually create a virtual machine and manually configure it (or configure it with the `configure_vm` stage from the script) and manually attach the existing virtual disk image.
