### ISSUE TITLE
Uninstallation and starting method

### ISSUE THREAD

**Issue by sundaslatif1** [myspaghetti/macos-virtualbox#594]
Please add guide about starting method of machine installed through this script. I  installed machine through this script but i am unable to see it in my Virtual box VMs. After installation it opened automatically, but after rebooting my host machine, I am unable to see it in my Virtual box. How I can start it?Moreover if I want to increase it's RAM after installation is it possible?Host OS is Ubuntu.

**Comment by myspaghetti** [comment]
This usually happens when the script is run with elevated privileges (with `sudo` or the `root` user for example) and then when VirtualBox GUI is launched from a different user it cannot access the VM. If that's the case, move the VM disk image from its elevated-privileges location to a user-accessible location, then manually create a virtual machine and manually configure it (or configure it with the `configure_vm` stage from the script) and manually attach the existing virtual disk image.
