### ISSUE TITLE
Script crashes Virtualbox during "Concatenating InstallESD.part00" so later installation fails

### ISSUE THREAD

**Issue by tomperchtold** [myspaghetti/macos-virtualbox#614]
Hi,

I have a problem with merging the part00 files together during the install process. It seems during the merging process using cat my VirtualBox crashes (maybe due to a heavy I/O load?) which leaves me of course with a corrupt dmg file which leads to a hang later when the startosinstall.sh/nvram.sh starts.

My InstallESD.dmg varies between 100 - 400 megs, depends on how long it stays alive.

I don't know why VirtualBox crashes here, installed the latest version but without the extpack. Log file does not show much.
And it happens on two different machines and on two different Linux distros (Fedora and Linux Mint).

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. macOS on VirtualBox with CPUs from 2020 and newer tend to crash. There's no list of supported CPUs, but generally they should be similar to ones from Intel Macs sold by Apple. See the script documentation about fitting one of the existing VirtualBox CPU profiles to your CPU, or manually generating the proper CPUID config.

Or, since you're running Linux, I heartily recommend using QEMU/KVM.

**Comment by tomperchtold** [comment]
Hello,
I found out what the real problem is: In the above mentioned machine where only 4 GB RAM installed. I assume Virtualbox ran into a OOM error during the merging process. Once I installed another 4 GB the merging process went through ...

**Comment by gostaj** [comment]
Just adding my own solution to more or less the same problem.
My **host** machine froze/hanged/crashed and restarted when concatenating the files.

Host: MacOS
`storage_size=35000` (I decreased it from the default which seemed ok since it says `minimum 22000`)

Solution: Use the default `storage_size=80000`, that works.
