### ISSUE TITLE
Virtualbox is not using hardware-supported virtualization features.

### ISSUE THREAD

**Issue by Prashansa1998** [myspaghetti/macos-virtualbox#615]
Checking that VirtualBox starts the virtual machine without errors.

Checking that VirtualBox uses hardware-supported virtualization.

Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
Exiting.

I am facing this issue while installing macos vm on my windows 10 machine. 
I tried the bcdedit command to turn off the hypervisor but still the issue is not resolved.

**Comment by arcini** [comment]
Try disabling virtual-machine-platform and windows-hypervisor-platform in windows features menu

**Comment by Prashansa1998** [comment]
<img width="862" alt="Capture" src="https://user-images.githubusercontent.com/111390881/185420869-46edc3fe-3932-443b-b98b-f52406fcd1f8.PNG">

**Comment by Prashansa1998** [comment]
It is turned off

**Comment by myspaghetti** [comment]
The specific software or feature that's blocking it is not reported by Windows. Core Isolation, Credential Guard, Device Guard, some virtualization software, and even some anti-virus software block VirtualBox from accessing VT-x/AMD-V. The script does not provide an exhaustive list of all software that blocks VirtualBox, and VirtualBox doesn't (and probably can't) specify which software is blocking it, so troubleshooting this issue is up to you. People have reported that running the following command as administrator and rebooting twice usually solves the issue:
```
bcdedit /set hypervisorlaunchtype off 
```

>I tried the bcdedit command to turn off the hypervisor but still the issue is not resolved.

Remember to reboot twice. If that doesn't work, then something else is blocking VirtualBox from accessing VT-x/AMD-V, or possibly the CPU doesn't support these features.
