### ISSUE TITLE
Does not work on Ubuntu 22.04 with VirtualBox 6.1.34-dfsg-3~ubuntu1.22.04.1

### ISSUE THREAD

**Issue by CaledoniaProject** [myspaghetti/macos-virtualbox#616]
I'm trying to use this script,

```
Delete existing virtual machine "macOS"? [y/N] y
Deleting macOS virtual machine.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

stage: create_vm

stage: check_default_virtual_machine

Checking that VirtualBox starts the virtual machine without errors.

Error while starting the virtual machine.
Exiting.
```

Then I entered the server with VNC, and start the "macOS" vm manually:

![111](https://user-images.githubusercontent.com/1357701/185581722-2e50aa96-cefd-44db-b552-22fd081b0817.jpg)

What should I do now?

**Comment by myspaghetti** [comment]
I assume the default VirtualBox instance on that server is headless? The script doesn't work with headless instances. If that's not the case, please attach the `VBox.log` file or the `macOS_troubleshoot.txt` file generated by `./macos-guest-virtualbox.sh troubleshoot` for troubleshooting.

**Comment by CaledoniaProject** [comment]
Thanks @myspaghetti, the script runs on XFCE desktop. I'll let you know if I got further errors.

**Comment by CaledoniaProject** [comment]
It stuck here:

![screen 2022-08-21 at 11 08 08](https://user-images.githubusercontent.com/1357701/185773612-c3575776-692f-4215-8b7e-6ed379a49537.jpg)

**Comment by myspaghetti** [comment]
The issue with headless VirtualBox is on the tracker (somewhere), I don't have any plans to troubleshoot it so it's marked as "won't fix"

The issue with `EXITBS` is documented on the readme and the script's `documentation` command, and is marked as "won't fix" because it requires cataloging many CPUs and their compatibility with macOS on VirtualBox, though if you hunt around the issue tracker you might a workaround for your CPU.
