### ISSUE TITLE
Monterey install to VirtualBox leaves Recovery Partition unbootable

### ISSUE THREAD

**Issue by CalculonPrime** [myspaghetti/macos-virtualbox#621]
Creating this issue because this project seems to be the best source of information for Monterey + VirtualBox on the web, so hopefully someone knowledgeable will drop in once search engines start returning the hit.  I'm somewhat confused about whether this is kosher with the project owner, as one earlier issue about the boot loop was closed "because the script doesn't support Monterey or Big sur," but a similar issue was allowed to remain open and gathered lots of useful posts that solved the issue for most involved.

Here, specifically, the issue is that after installing Monterey to VB, you can't boot into the Recovery Partition using "boot from file" in the VirtualBox BIOS, because boot.efi is missing.  Instead there is either nothing shown, or a bunch of similar files that don't work (_boot.efi, etc.).  VMware has a similar bug logged against it, so what I assume happened is that starting in Big Sur, Apple made some formatting change to the Recovery partition, and VMware and VirtualBox were caught with their pants down.

You can see my original comment about this in the bootloop thread [here](https://github.com/myspaghetti/macos-virtualbox/issues/484#issuecomment-1191053934).

BTW, there are lots of suggestions on how to "work around" this by simply creating another Monetery installation, perhaps on an external USB, to work as a Recovery partition.  I don't want that.  i want the stock, included Recovery partition to work.

**Comment by myspaghetti** [comment]
I'm fine with this, but keep in mind that this is not a troubleshooting forum and after a week or two I'll close the issue whether or not it's resolved.

**Comment by CalculonPrime** [comment]
OK, I'm curious.  What allowed [this issue](https://github.com/myspaghetti/macos-virtualbox/issues/484) to remain open for 4 months (roughly)?

**Comment by myspaghetti** [comment]
There's no grand design with my issue tracking, it's all pretty haphazard. I tend to be more liberal with issues with upgrades because incorporating newer versions of macOS into the script is the most popular enhancement request. [A solution exists](https://github.com/myspaghetti/macos-virtualbox/issues/547#issuecomment-1058861541) but I'm not motivated to work on it, although it should be straightforward to implement. Meanwhile, issues with upgrading get a bit of a grace period on the issue tracker even though they're not technically issues with the script.
