### ISSUE TITLE
Works smoothly for months, then suddenly got EXITBS with no changes.

### ISSUE THREAD

**Issue by ArsenicBismuth** [myspaghetti/macos-virtualbox#622]
As the title implied, months ago I got EXITBS and it was solvable with:
`VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"`

I got it running for months without any problem, even got to install Monterey.

Today, weeks after not using it, I got EXITBS again. No changes and even trying all the different kind of snapshots that was 100% working at that time (Catalina & Monterey). Also tried resetting the CPU profile. What would be the cause to this behavior change?

Screenshot:
![image](https://user-images.githubusercontent.com/19264532/190558777-7ed6421f-0f53-4e3a-8fcd-965abea98a6b.png)

**Comment by thesipguy** [comment]
This happened to me approx 6 times, every time I dont use the VM for a few weeks I get a error, I got different errors every time, sometimes it got stuck in a panic loop, sometimes it got stuck at the EXITBS:START I opened a ticket a while ago and the maintainer decided it was a question and not a bug while its very clear its a bug, I assume the maintainer does not know how to fix it and instead closes the ticket, I gave up on it because every time I reinstalled it it took me a full day to upgrade the mac os because xcode wouldnt install on the current version, and installing xcode and Android Studio.

**Comment by myspaghetti** [comment]
Post-install issues are out of the scope of the script. All the script does is install macOS on VirtualBox. The scope of the script ends with the installer completing its tasks and macOS booting on VirtualBox. The README should make it clear that issues with macOS or VirtualBox are outside the scope of this script. Hence this is a question about non-script issues.
